Rails.application.routes.draw do

    # root 'users#new'
     root    'static_pages#home'
   get  'believe'             => 'static_pages#believe'
   get  'help'                => 'static_pages#help'
   get  'about'               => 'static_pages#about'
   get  'contact'             => 'static_pages#contact'
   get  'menu1'               => 'static_pages#menu1' 
   get  'menu2'               =>  'static_pages#menu2'
   get  'menu3'               =>  'static_pages#menu3'
   get  'menu4'               =>  'static_pages#menu4'
   get  'petersalem'          =>       'static_pages#petersalem'
   get  'princewhipple'       =>        'static_pages#princewhipple'
   #get 'static_pages/olivercromwell'
   get  'jamesarmistead'            =>   'static_pages#jamesarmistead'
   get  'historianswilliamnell'     =>  'static_pages#historianswilliamnell'
   get  'frederickdouglass'         =>     'static_pages#frederickdouglass'
   get  'stthomaschurch'          =>      'static_pages#stthomaschurch'
   get  'revabsalomjones'         =>      'static_pages#revabsalomjones'
   get  'revrichardallen'          =>      'static_pages#revrichardallen'
   get  'dredscott'                =>        'static_pages#dredscott'
  get 'emancipation'          =>   'static_pages#emancipation'
  get 'africanslavery'            =>   'static_pages#africanslavery'
  get 'revhenrygarnet'           =>   'static_pages#revhenrygarnet'
  get 'attorneyjohnrock'             =>'static_pages#attorneyjohnrock'
  get 'tencommandments'         =>     'static_pages#tencommandments'
  get 'reconstruction'          =>    'static_pages#reconstruction'
  get 'republicanusrepjosephhrainey'    =>    'static_pages#republicanusrepjosephhrainey'
  get 'fisrtsevenelected'              =>     'static_pages#fisrtsevenelected'
  get 'revrevelsthreeblackregiments'   =>       'static_pages#revrevelsthreeblackregiments'



  get 'josiahwalls'                        =>      'static_pages#josiahwalls'
  get 'republicansenatorhiramrrevels'       =>     'static_pages#republicansenatorhiramrrevels'
  get 'republicansenatorblanchekbruce'          => 'static_pages#republicansenatorblanchekbruce'
  get 'republicanusreprobertbelliot'       =>      'static_pages#republicanusreprobertbelliot'
  get 'republicanusrepjosephhrainey2'        =>    'static_pages#republicanusrepjosephhrainey2'
  get 'republicanusreprichardcain'            =>   'static_pages#republicanusreprichardcain'
  get 'blackamericansoldiers'                =>    'static_pages#blackamericansoldiers'
  get 'republicanusrepjohnrlynch'             =>   'static_pages#republicanusrepjohnrlynch'
  get 'republicanusrepjosiahwalls'             =>  'static_pages#republicanusrepjosiahwalls'
  get 'republicanusrepjosephhrainey3'          =>  'static_pages#republicanusrepjosephhrainey3'
  get 'republicanusrepjohnrlynch2'             =>  'static_pages#republicanusrepjohnrlynch2'
  get 'republicanusreprobertbrownelliot'       =>  'static_pages#republicanusreprobertbrownelliot'
  get 'repjamesrapier'                   =>        'static_pages#repjamesrapier'
  get 'revcharlescljackson'                   =>   'static_pages#revcharlescljackson'
  get 'revrichardallen2'                     =>    'static_pages#revrichardallen2'
  get 'reprichardcain'                       =>    'static_pages#reprichardcain'
  get 'repjosephhrainey4'                     =>   'static_pages#repjosephhrainey4'
  get 'frederickdouglas2'                    =>    'static_pages#frederickdouglas2'
  get 'tommoss'                            =>      'static_pages#tommoss'
  get 'fredrickmorroweisenhower'       =>          'static_pages#fredrickmorroweisenhower'
  get 'drmartinlutherking'                  =>     'static_pages#drmartinlutherking'
  get 'repjcwatts'                     =>          'static_pages#repjcwatts'
  get 'reprobertbrownelliot'                =>     'static_pages#reprobertbrownelliot'
  get 'frederickdouglas3'                 =>       'static_pages#frederickdouglas3'
  get 'revfrancisgrimke'                     =>    'static_pages#revfrancisgrimke'
  get 'firstsevenwithverses'                   =>  'static_pages#firstsevenwithverses'

   get 'signup' => 'users#new'
    resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
